### ISSUE TITLE
Issue about some operation about hop node

### ISSUE THREAD

**Issue by Liamgettingbetter** [SmartMeshFoundation/SmartRaiden#27]
We should have countermeasures when channel initiator or mediator have received `SettleRequest` and `WithdrawRequest`. Such as wen channel initiator received `SettleRequest` or `withdrawRequest` at that time he should make a response to his channel partner, and wait for related event occurs on-chain (just like receiving `AnnounceDisposed` message). 
- At the time that B sending `MediatedTransfer` to C receives `WithdrawRequest/SettleRequest`, he should not submit `withdraw/settle` request on behalf of C, because there is risk that participant A and C collude with each other and let B to be a scapegoat, which is unreasonable.

- StateManager is in charge of handling with `Withdraw` and `CooperativeSettle` on-chain, if a channel route is impassable, it should alter to another secure route.

- `Settle` on chain has no need to be dealt with, for the reason that if channel partner chooses to close the channel once he received `MediatedTransfer`, and wait for channel settle, then the hash lock in this channel gets expired 100%, and to make this transfer failed and this lock gets removed.

**Comment by nkbai** [comment]
12. 发起方/中间节点在收到 SettleRequest 以及 WithdrawRequest 应该有相应的处理. 比如发起方收到 SettleRequest/ withdrawRequest,这时候应该给对方 response, 等确认链上相应的事件确定发生(如同收到了 AnnouceDisposed 消息). 此时可以认为当前选定的路由肯定是走不通了(如同收到了 AnnounceDisposed).  
    - 针对我在发送 MediatedTransfer 以后收到了WitdhrawRequest/SettleRequest, 这时候不应该提对方 withdraw/settle, 因为这可能被利用,比如A,C 串谋,每次都通过 A-B-C 交易的方式来让 B 来做 withdraw/settle, 这不合理.  
    - StateManager要针对链上发生的 Withdraw 以及 CoOperativeSettle 事件进行处理,认为选定的路径不通,可以安全的走其他路径
    - 而对链上发生的 Settle 事件无需处理,因为如果是对方收到 MediatedTransfer 以后,选择 close, 然后等待,然后 settle, 那么这个锁必定会超时,从而导致此交易失败,而被移除.
