### ISSUE TITLE
No net switch down, expired locks will not be processed

### ISSUE THREAD

**Issue by dognie** [SmartMeshFoundation/SmartRaiden#66]
## Scenario:
When I switch to the nonetwork state, I should refuse to accept mediated transfer, only accept direct transfer.（`It only exists in an expired MTR scenario`.）

- Now Bob has switched to the state of no net.`/api/1/switch/true`
- Alice send Bob to mediated transfer 
- Bob  refused to accept, giving log `“MessageHandler.onMessage deny any mediated transfer when there is no internet connection”` all of which are logical.
- Strangely enough, Alice sends a MTR to Bob all the time. When Bob switches back to the netted state,`/api/1/switch/false`  it receives MTR without any processing, and Alice does not make any processing, even if the lock has expired. At this point, Alice and Bob have different channel states, and the channel is invalid, which does not conform to the design principle.

**Comment by Chuck52** [comment]
fix at [#68](https://github.com/SmartMeshFoundation/SmartRaiden/pull/68/commits/322601321db1742549ec212750258057199bc729)
